name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # Fix for GitHub token permission issue

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: git-rat
          outputs: dist/snake.svg

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output  # Ensure 'output' branch exists
          folder: dist
